#!/usr/bin/env python3

# executed in geocat-comp miniconda env

import numpy as np
from geocat.comp import linint2

tmax = np.load('tmax_2020.npy') # gridmet 2020 tmax converted to numpy array

oldlat = np.arange(25.06667,49.401,0.0416667)
oldlon = np.arange(-124.7667,-67.05832,0.0416667)
newlat = np.arange(25,50.1,1)
newlon = np.arange(-125,-66,1)

regridded = linint2(tmax, newlon, newlat, xi=oldlon, yi=oldlat, icycx=False)

np.save('tmax_2020_regridded',regridded)
